### ISSUE TITLE
Application Error on Heroku

### ISSUE THREAD

**Issue by Sticksword** [TwilioDevEd/survey-node#1]
Hi Twilio Team,

I read through the interactive tutorial and tried to deploy the example through the Heroku template you guys provided in the readme.md but for some reason I get an application error when I go to the landing page. Any ideas as to why? When I run locally, it appears that 27017 is undefined which means that I don't have a local instance of MongoDB running. However, from Heroku, I saw that a mongoDB instance is running with MongoLabs. What could possibly be the problem then on my Heroku deployed application? Here's the link with the message.
https://twilio-hackprinceton-sample.herokuapp.com/landing.html

Thank you!
Michael

**Comment by pchinjr** [comment]
I have the same problem. I have tried to run it locally, but am unable to trouble shoot it as well.

**Comment by acamino** [comment]
Thanks for reporting the issue. Looks like the issue you're experimenting was caused by the _mongoose_ version this used in this application.

I've just update the dependency in fba093d. Hopefully you'll be able to run the application either on Heroku or locally.
