### ISSUE TITLE
Survey stuck at second question, does not accept DTMF

### ISSUE THREAD

**Issue by pundaripothini** [TwilioDevEd/survey-node#7]
Been troubleshooting for over a day and no matter how many times i call back the survey gets stuck at the 2nd question. I'm trying to figure out how to add defaults in case a question fails and move on to the 2nd question. I think it's not a good practice to have callers get stuck in the same question for some reason the survey breaks.

**Comment by jothikannan** [comment]
@pundaripothini I am also having the same issue, found any solution?

**Comment by pundaripothini** [comment]
No solution, I abandoned this project and rebuilding everything
from scratch.

**Comment by joliveros** [comment]
Hi @pundaripothini,

It looks like the dependencies needed updating. I also added some better logging to help in debugging. 
Please have a look at `master` branch and let me know if you have any further issues running this app.

Thank you

**Comment by jothikannan** [comment]
Now it's working fine, thanks :)
